//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_MVC_Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorty_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categorty_Type()
        {
            this.Wardrobe_Items = new HashSet<Wardrobe_Items>();
        }
    
        public int TypeId { get; set; }
        public string Categories { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wardrobe_Items> Wardrobe_Items { get; set; }
    }
}
