//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2017_MVC_Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wardrobe_Items
    {
        public int ItemID { get; set; }
        public int TypeID { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public string Color { get; set; }
        public string Season { get; set; }
        public string Occasion { get; set; }
    
        public virtual Categorty_Type Categorty_Type { get; set; }
    }
}
